version: "3.8"

services:
  service1:
    build: ./app1
    container_name: chatbot
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATA_SERVICE_BASE_URL=http://service2:8001
    networks:
      - network
    depends_on:
      - service2

  service2:
    build: ./app2
    container_name: data_service
    env_file:
      - .env
    environment:
      - DATA_FILE_PATH=./data/data.json
    ports:
      - "8001:8001"
    networks:
      - network

networks:
  network:
    driver: bridge
